mod_version=1.0.13
minecraft_version=26.2

journeymap_webmap_version=1.2-SNAPSHOT
journeymap_api_version=26.2-2.0.0-SNAPSHOT
group_id=info.journeymap_webmap
name=JourneyMap WebMap
mod_id=journeymap_webmap
base_name=journeymap-webmap

release_type=release

# Mappings
mappings_channel=parchment
mappings_date=2025.10.12
mappings_mc_version=26.1.2

# Forge
forge_version=65.0.0
journeymap_forge_version=8283777

# Neoforge https://neoforged.net/
neoforge_version=26.2.0.0-beta
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
journeymap_neoforge_version=8283778

# Fabric
fabric_api_version=0.152.1+26.2
fabric_loader_version=0.19.3
journeymap_fabric_version=8283776

javalin_version=6.7.0

curseforge_project_id=793035
modrinth_project_id=YaZ1fUTg

git_website=https://github.com/TeamJM/journeymap-webmap

# Gradle
java_version=25
dateFormat=yyyy-MM-dd-HH:mm:ss
org.gradle.jvmargs=-Xms1G -Xmx3G -Dnojline/
org.gradle.daemon=true
org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-25.0.2.10-hotspot
