import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.accesstransformers' version '5.0.2'
    id 'net.minecraftforge.gradle' version '7.0.0-beta.55'
    id "net.darkhax.curseforgegradle" version "1.+"
    id "com.modrinth.minotaur" version "2.+"
    id 'com.gradleup.shadow'
}

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}
configurations {
    shade
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.10'
    compileOnly group: 'info.journeymap', name: 'journeymap-api-forge', version: "${project.journeymap_api_version}-${project.minecraft_version}-SNAPSHOT", changing: true
    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '2.2.21'

    shade group: 'info.journeymap', name: 'webmap-client', version: project.journeymap_webmap_version, changing: true

    //external libs shade
    shade group: 'io.javalin', name: 'javalin', version: project.javalin_version
    shade group: 'org.slf4j', name: 'slf4j-simple', version: '2.0.16'

    testCompileOnly group: 'info.journeymap', name: 'journeymap-api-forge', version: "${project.journeymap_api_version}-${project.minecraft_version}-SNAPSHOT", changing: true

}

minecraft {
    mappings channel: project.mappings_channel, version: "${project.mappings_mc_version}-${project.mappings_date}"

    accessTransformers = '../../../../common/src/main/resources/META-INF/accesstransformer.cfg'

    runs {
        configureEach {
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }
        register('client') {
            workingDir.convention layout.projectDirectory.dir("run/client")
        }
        register('server') {
            workingDir.convention layout.projectDirectory.dir("run/server")
            args "nogui"
        }
    }
}
//sourceSets.main.resources.srcDir 'src/generated/resources'
//
//sourceSets.each {
//    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
//    it.output.resourcesDir = dir
//    it.java.destinationDirectory = dir
//}


shadowJar {
    mustRunAfter(processTestResources)
    archiveFileName.set("${archiveBaseName.get()}-${archiveVersion.get()}.${archiveExtension.get()}")
    configurations = [project.configurations.shade]
    archiveClassifier.set("")
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    dependencies {
        exclude("META-INF/maven/**")
        exclude("META-INF/services/org.*")
        exclude("META-INF/services/jakarta.*")
        exclude(dependency("org.ow2.asm:.*:.*"))
    }
    minimize {
        // API has utility classes that must be included
        exclude(dependency("info.journeymap:.*:.*"))
        exclude(dependency("org.slf4j:.*:.*"))
    }
    relocate "kotlin", "info.journeymap.shaded.kotlin.kotlin"
    relocate "jakarta", "info.journeymap.shaded.jakarta"
    relocate "javax.servlet", "info.journeymap.shaded.org.javax.servlet"
    relocate "org.intellij", "info.journeymap.shaded.org.intellij"
    relocate "org.jetbrains", "info.journeymap.shaded.org.jetbrains"
    relocate "org.slf4j", "info.journeymap.shaded.org.slf4j"
    relocate "org.eclipse", "info.journeymap.shaded.org.eclipse"

    relocate "io.javalin", "info.journeymap.shaded.io.javalin"

    exclude 'dummyThing'
    exclude 'LICENSE.txt'
}


tasks.assemble.dependsOn shadowJar

artifacts {
    archives shadowJar
}


// Automated upload to CurseForge for the win!
if (!project.hasProperty("curseForgeApiKey")) {
    ext.curseForgeApiKey = project.findProperty("curseforge_api_key") ?: "notset"
}
if (!project.hasProperty("modrinthApiKey")) {
    ext.modrinthApiKey = project.findProperty("modrinth_api_key") ?: "notset"
}

tasks.register("publishCurseForge", TaskPublishCurseForge) {
    apiToken = "${curseForgeApiKey}"
    def mainFile = upload(curseforge_project_id, shadowJar)
    mainFile.displayName = "${project.mod_id}-${version}+${project.name}"
    mainFile.releaseType = release_type
    mainFile.addModLoader("Forge")
    mainFile.addJavaVersion("Java 25")
    mainFile.addGameVersion("${project.minecraft_version}")
    mainFile.addRelation("journeymap", "requiredDependency")
    mainFile.changelogType = "html"
    mainFile.changelog = file("$project.buildDir/doc/changelog.html")
}

tasks.modrinth.dependsOn(tasks.build)

modrinth {
    token = "${modrinthApiKey}"
    projectId = modrinth_project_id
    versionNumber = "${version}-forge"
    versionName = "${project.mod_id}-${version}+${project.name}"
    versionType = release_type
    uploadFile = shadowJar
    gameVersions = ["${project.minecraft_version}"]
    loaders = ["forge"]
    changelog = file("$project.buildDir/doc/changelog.html").exists() ? file("$project.buildDir/doc/changelog.html").text : null
    dependencies {
        required.project "journeymap"
    }
}

tasks.withType(PublishToMavenRepository) { task ->
    task.dependsOn shadowJar
}
tasks.named('assemble').configure { dependsOn 'shadowJar' }

jar.finalizedBy 'shadowJar'

publishing {
    repositories {
        maven {
            name = "JourneyMap"
            url = uri("https://jm.gserv.me/repository/maven-releases/")

            credentials {
                username = project.findProperty("journeymap.user") ?: System.getenv("JOURNEYMAP_WEB_USER")
                password = project.findProperty("journeymap.password") ?: System.getenv("JOURNEYMAP_WEB_PASSWORD")
            }
        }
    }

    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId base.archivesName.get()
            version "${project.version}-forge"
            artifact shadowJar
        }
    }
}
