plugins {
    id 'idea'
    id 'java'
    id 'net.neoforged.moddev'
    id 'maven-publish'
}


version = "${project.mod_version}+${project.minecraft_version}"
def modVersion = "${project.mod_version}"

group = project.group_id
base.archivesName = project.base_name

configurations {
    shade
}


neoForge {
    neoFormVersion = neo_form_version
    addModdingDependenciesTo(sourceSets["test"])
}

dependencies {
    implementation 'org.jetbrains:annotations:20.1.0'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'info.journeymap', name: 'journeymap-api-common', version: "${project.journeymap_api_version}-${project.minecraft_version}-SNAPSHOT", changing: true
    // for annotations
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation group: 'io.javalin', name: 'javalin', version: project.javalin_version
}

task processDocs(type: Copy) {
    // update docs
    from(file("/doc/")) {
        include '*.html'
        expand 'version': project.version,
                'date': getDate(),
                'mcversion': project.minecraft_version,
                'loaderversion': project.forge_version,
                'loadername': "Forge"
    }
    into 'build/doc'
}
