plugins {
    id 'net.neoforged.moddev'
    id 'multiloader-common'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    // While this location can be changed, it is recommended for
    // common and neoforge to share an accesstransformer file
    // and this location is hardcoded in FML
    // https://github.com/neoforged/FancyModLoader/blob/a952595eaaddd571fbc53f43847680b00894e0c1/loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFile.java#L118
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    addModdingDependenciesTo(sourceSets["test"])
}

dependencies {
    implementation 'org.jetbrains:annotations:20.1.0'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'info.journeymap', name: 'journeymap-api-common', version: "${project.journeymap_api_version}", changing: true
    // for annotations
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation group: 'io.javalin', name: 'javalin', version: project.javalin_version
}
