modLoader="javafml"
loaderVersion="[2,)" #
issueTrackerURL="https://github.com/TeamJM/journeymap/issues"
license="All rights reserved"

[[mixins]]
config = "journeymap_webmap.mixins.json"

[[mods]]
modId="journeymap_webmap"
version="${version}"
displayName="JourneyMap WebMap"
updateJSONURL="https://forge.curseupdate.com/793035/journeymap-web-map"
displayURL="http://journeymap.info"
logoFile="journeymapwebmap.png"
credits="Techbrew, Mysticdrew, gdude"
authors="Techbrew, Mysticdrew"

description='''
Client WebMap for Journeymap. Built: ${date}.
'''

[[dependencies.journeymap_webmap]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.0-beta,)"
side="BOTH"

[[dependencies.journeymap_webmap]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
side="BOTH"

[[dependencies.journeymap_webmap]]
modId="journeymap"
type = "required"
versionRange="[26.2-6.0.0,)"
side="BOTH"
