import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'net.neoforged.moddev'
    id 'multiloader-loader'
    id 'com.gradleup.shadow'
    id 'net.darkhax.curseforgegradle' version '1.+'
    id "com.modrinth.minotaur" version "2.+"
}


configurations {
    shade
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    addModdingDependenciesTo(sourceSets["test"])
    runs {
        configureEach {
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            jvmArgument("-Dmixin.debug.export=true")
        }
        client {
            client()
            gameDirectory = project.file('run/client')
        }
        server {
            server()
            gameDirectory = project.file("run/server")
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation group: "info.journeymap", name: "journeymap-api-neoforge", version: "${project.journeymap_api_version}-${project.minecraft_version}-SNAPSHOT", changing: true

    implementation group: 'io.javalin', name: 'javalin', version: project.javalin_version
    shade group: 'info.journeymap', name: 'webmap-client', version: project.journeymap_webmap_version, changing: true
    implementation group: 'io.javalin', name: 'javalin', version: project.javalin_version

    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '2.1.20'
    //external libs shade
    shade group: 'io.javalin', name: 'javalin', version: project.javalin_version
    shade group: 'org.slf4j', name: 'slf4j-simple', version: '2.0.16'

}

tasks.assemble.dependsOn shadowJar
jar.finalizedBy('shadowJar')

shadowJar {
    mustRunAfter(processTestResources)
    archiveFileName.set("${archiveBaseName.get()}-${archiveVersion.get()}.${archiveExtension.get()}")
    configurations = [project.configurations.shade]
    archiveClassifier.set("")
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    dependencies {
        exclude("META-INF/maven/**")
        exclude("META-INF/services/org.*")
        exclude("META-INF/services/jakarta.*")
        exclude(dependency("org.ow2.asm:.*:.*"))
    }
    minimize {
        // API has utility classes that must be included
        exclude(dependency("info.journeymap:.*:.*"))
        exclude(dependency("org.slf4j:.*:.*"))
    }

    relocate "kotlin", "info.journeymap.shaded.kotlin.kotlin"
    relocate "jakarta", "info.journeymap.shaded.jakarta"
    relocate "javax.servlet", "info.journeymap.shaded.org.javax.servlet"
    relocate "org.intellij", "info.journeymap.shaded.org.intellij"
    relocate "org.jetbrains", "info.journeymap.shaded.org.jetbrains"
    relocate "org.slf4j", "info.journeymap.shaded.org.slf4j"
    relocate "org.eclipse", "info.journeymap.shaded.org.eclipse"

    relocate "io.javalin", "info.journeymap.shaded.io.javalin"

    exclude 'dummyThing'
    exclude 'LICENSE.txt'
}

//jar {
//    archiveClassifier.set('slim')
//    dependsOn 'processDocs'
//    manifest {
//        attributes([
//                "Specification-Title"     : project.name,
//                "Specification-Vendor"    : project.group_id,
//                "Specification-Version"   : "1", // We are version 1 of ourselves
//                "Implementation-Title"    : project.name,
//                "Implementation-Version"  : "${version}",
//                "Implementation-Vendor"   : project.group_id,
//                "Implementation-URL"      : "http://journeymap.info",
//                "Implementation-Timestamp": getDate(),
//                "FMLAT"                   : "accesstransformer.cfg",
//        ])
//    }
//}

artifacts {
    archives shadowJar
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Automated upload to CurseForge for the win!
if (!project.hasProperty("curseForgeApiKey")) {
    ext.curseForgeApiKey = project.findProperty("curseforge_api_key") ?: "notset"
}
if (!project.hasProperty("modrinthApiKey")) {
    ext.modrinthApiKey = project.findProperty("modrinth_api_key") ?: "notset"
}

tasks.register("publishCurseForge", TaskPublishCurseForge) {

    apiToken = "${curseForgeApiKey}"
    def mainFile = upload(curseforge_project_id, shadowJar)
    mainFile.displayName = "${project.mod_id}-${version}+${project.name}"
    mainFile.releaseType = release_type
    mainFile.addModLoader("NeoForge")
    mainFile.addJavaVersion("Java 25")
    mainFile.addGameVersion("${project.minecraft_version}")
    mainFile.addRelation("journeymap", "requiredDependency")
    mainFile.changelogType = "html"
    mainFile.changelog = file("$project.buildDir/doc/changelog.html")
}


tasks.modrinth.dependsOn(tasks.assemble)

modrinth {
    token = "${modrinthApiKey}"
    projectId = modrinth_project_id
    versionNumber = "${version}-neoforge"
    versionName = "${project.mod_id}-${version}+${project.name}"
    versionType = release_type
    uploadFile = shadowJar
    gameVersions = ["${project.minecraft_version}"]
    loaders = ["neoforge"]
    changelog = file("$project.buildDir/doc/changelog.html").exists() ? file("$project.buildDir/doc/changelog.html").text : null
    dependencies {
        required.project "journeymap"
    }
}

// Ensure build is done prior to cursegradle tasks
project.afterEvaluate {
    project.tasks.findAll { task ->
        (task.name.startsWith('curseforge') || task.name.startsWith('modrinth'))
                && (task.name != 'curseforge' || task.name != 'modrinth')
    }.each { projectTask ->
        projectTask.dependsOn build
    }
}

TaskCollection.metaClass.excludingNeoTasks = { ->
    delegate.matching { !it.name.startsWith("neo") }
}

tasks.withType(JavaCompile).excludingNeoTasks().configureEach {
    source(project(":common").sourceSets.main.allSource)
}

publishing {
    repositories {
        maven {
            name = "JourneyMap"
            url = uri("https://jm.gserv.me/repository/maven-releases/")

            credentials {
                username = project.findProperty("journeymap.user") ?: System.getenv("JOURNEYMAP_WEB_USER")
                password = project.findProperty("journeymap.password") ?: System.getenv("JOURNEYMAP_WEB_PASSWORD")
            }
        }
    }

    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId base.archivesName.get()
            version "${project.version}-forge"
            artifact shadowJar
        }
    }
}
