name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Build
        run: /bin/sh ./gradlew build

      - name: Gradle Publish
        run: /bin/sh ./gradlew -Pjourneymap.user=${{ secrets.JOURNEYMAP_WEB_USER }} -Pjourneymap.password=${{ secrets.JOURNEYMAP_WEB_PASSWORD }} publish
